language: node_js
node_js:
- "4.2"
- "0.12"
- "0.11"
- "0.10"
- "iojs-v2.5.0"
- "iojs-v1.0.4"

addons:
  apt:
    packages:
    - gcc-4.8
    - build-essential
    - libudev-dev

before_script:
- npm install -g istanbul
- npm install -g istanbul-coveralls

after_success:
- npm run cover
